name: CI

on:
  push:
    branches:
      - cdk-master
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
     - uses: coursier/cache-action@v6
     - uses: actions/setup-java@v2.5.0
       with:
         distribution: temurin
         java-version: 17
         check-latest: true
      - name: Lint code
        run: sbt check
      - name: Mdocs check
        run: sbt docs/mdoc

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '17']
        scala: ['2.12.15', '2.13.8', '3.1.1']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test
